//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessingApplication.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPaymentDetail()
        {
            this.ShipmentItemDetails = new HashSet<ShipmentItemDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PaymentItem { get; set; }
        public Nullable<bool> IsActiveMembership { get; set; }
        public Nullable<bool> IsUpgradeMembership { get; set; }
        public Nullable<decimal> ApplicableAgentCommision { get; set; }
        public Nullable<bool> IsActivationUpgradeEmailSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItemDetail> ShipmentItemDetails { get; set; }
    }
}
